import type * as THREE from 'three';
import type { OrbitControls } from 'three/addons/controls/OrbitControls.js';

export type SetStatus = (message: string) => void;

export interface ARDomElements {
	statusButton: HTMLButtonElement;
	modelNameEl: HTMLElement;
	modelSelectEl: HTMLSelectElement;
	canvasContainer: HTMLElement;
	desktopCanvasContainer: HTMLElement;
	mobilePreArShellEl: HTMLElement;
	mobileArShellEl: HTMLElement;
	mobilePreArCanvasContainer: HTMLElement;
	mobilePreArModelSelectEl: HTMLSelectElement;
	mobilePreArStageSelectEl: HTMLSelectElement;
	mobilePreArProjectNameEl: HTMLElement;
	mobilePreArCurrentModelEl: HTMLElement;
	mobilePreArCurrentStageEl: HTMLElement;
	mobilePreArRuntimeStatusEl: HTMLElement;
	mobilePreArPreviewStatusEl: HTMLElement;
	mobilePreArSupportBadgeEl: HTMLElement;
	mobilePreArSupportMessageEl: HTMLElement;
	mobilePreArLayerListEl: HTMLElement;
	mobilePreArEnterArButton: HTMLButtonElement;
	xrButtonWrap: HTMLElement;
	mobileDisplayModeSelectEl: HTMLSelectElement;
	mobileRightToolsEl: HTMLElement;
	mobileBottomNavEl: HTMLElement;
	mobileArGuidanceEl: HTMLElement;
	mobileArGuidanceTitleEl: HTMLElement;
	mobileArGuidanceBodyEl: HTMLElement;
	mobileArPrimaryBarEl: HTMLElement;
	mobileArExitButton: HTMLButtonElement;
	mobileArPlaceButton: HTMLButtonElement;
	browsePropertyActionsEl: HTMLElement;
	browseShowDetailsButton: HTMLButtonElement;
	browseAddInspectionButton: HTMLButtonElement;
	registrationOverviewCardEl: HTMLElement;
	registrationOverviewActionRowEl: HTMLElement;
	registrationOpenManualButton: HTMLButtonElement;
	registrationOpenControlButton: HTMLButtonElement;
	registrationSaveButton: HTMLButtonElement;
	registrationAdjustmentPanelEl: HTMLElement;
	registrationPrecisionPanelEl: HTMLElement;
	inspectionOverviewCardEl: HTMLElement;
	inspectionStartFormButton: HTMLButtonElement;
	inspectionViewListButton: HTMLButtonElement;
	inspectionFormPanelEl: HTMLElement;
	propertyCloseButton: HTMLButtonElement;
	propertyNameEl: HTMLElement;
	propertyStatusBadgeEl: HTMLElement;
	propertyTypeEl: HTMLElement;
	propertyDiameterEl: HTMLElement;
	propertyMaterialEl: HTMLElement;
	propertyDepthEl: HTMLElement;
	propertyStatusEl: HTMLElement;
	propertyRemarkEl: HTMLElement;
	resetPlacementButton: HTMLButtonElement;
	enableCoarseButton: HTMLButtonElement;
	refreshGeoButton: HTMLButtonElement;
	toolLayersButton: HTMLButtonElement;
	toolMeasureButton: HTMLButtonElement;
	modeBrowseButton: HTMLButtonElement;
	modeRegistrationButton: HTMLButtonElement;
	modeTimelineButton: HTMLButtonElement;
	modeInspectionButton: HTMLButtonElement;
	mobileTopbarEl: HTMLElement;
	mobileTopTitleEl: HTMLElement;
	mobileTopSubtitleEl: HTMLElement;
	mobileDrawerAreaEl: HTMLElement;
	mobileDrawerToggleButton: HTMLButtonElement;
	mobileDrawerToggleLabelEl: HTMLElement;
	registrationStatusEl: HTMLElement;
	registrationStatusDetailEl: HTMLElement;
	browsePanelEl: HTMLElement;
	manualPanelEl: HTMLElement;
	timelinePanelEl: HTMLElement;
	inspectionPanelEl: HTMLElement;
	manualLeftButton: HTMLButtonElement;
	manualRightButton: HTMLButtonElement;
	manualFrontButton: HTMLButtonElement;
	manualBackButton: HTMLButtonElement;
	manualUpButton: HTMLButtonElement;
	manualDownButton: HTMLButtonElement;
	manualYawLeftButton: HTMLButtonElement;
	manualYawRightButton: HTMLButtonElement;
	manualScaleUpButton: HTMLButtonElement;
	manualScaleDownButton: HTMLButtonElement;
	manualSaveButton: HTMLButtonElement;
	manualResetButton: HTMLButtonElement;
	manualValuePositionEl: HTMLElement;
	manualValueYawEl: HTMLElement;
	manualValueScaleEl: HTMLElement;
	precisionSourceSelectEl: HTMLSelectElement;
	precisionSourceArmButton: HTMLButtonElement;
	precisionTargetConfirmButton: HTMLButtonElement;
	precisionPairAddButton: HTMLButtonElement;
	precisionSolveButton: HTMLButtonElement;
	precisionSaveButton: HTMLButtonElement;
	precisionClearButton: HTMLButtonElement;
	precisionSourceCurrentEl: HTMLElement;
	precisionTargetCurrentEl: HTMLElement;
	precisionPairCountEl: HTMLElement;
	precisionRmsEl: HTMLElement;
	precisionWorkflowStatusEl: HTMLElement;
	precisionPairListEl: HTMLElement;
	timelineCurrentStageEl: HTMLElement;
	timelinePrevButton: HTMLButtonElement;
	timelineNextButton: HTMLButtonElement;
	timelinePlayButton: HTMLButtonElement;
	timelineStageButtons: HTMLButtonElement[];
	inspectionTypeEl: HTMLSelectElement;
	inspectionSeverityEl: HTMLSelectElement;
	inspectionNoteEl: HTMLTextAreaElement;
	inspectionPhotoButton: HTMLButtonElement;
	inspectionSaveButton: HTMLButtonElement;
	desktopProjectNameEl: HTMLElement;
	desktopModelSelectEl: HTMLSelectElement;
	desktopCurrentModelEl: HTMLElement;
	desktopRuntimeStatusEl: HTMLElement;
	desktopModelFileEl: HTMLElement;
	desktopPipeListEl: HTMLElement;
	desktopLayerListEl: HTMLElement;
	desktopStageListEl: HTMLElement;
	desktopPreviewBadgeEl: HTMLElement;
	desktopDisplayModeSelectEl: HTMLSelectElement;
	desktopParamGpsEl: HTMLElement;
	desktopParamEnuEl: HTMLElement;
	desktopParamPositionEl: HTMLElement;
	desktopParamQuaternionEl: HTMLElement;
	desktopParamScaleEl: HTMLElement;
	desktopParamRmsEl: HTMLElement;
	desktopPrecisionSourceSelectEl: HTMLSelectElement;
	desktopPrecisionSourceArmButton: HTMLButtonElement;
	desktopPrecisionTargetConfirmButton: HTMLButtonElement;
	desktopPrecisionPairAddButton: HTMLButtonElement;
	desktopPrecisionSolveButton: HTMLButtonElement;
	desktopPrecisionSaveButton: HTMLButtonElement;
	desktopPrecisionClearButton: HTMLButtonElement;
	desktopPrecisionSourceCurrentEl: HTMLElement;
	desktopPrecisionTargetCurrentEl: HTMLElement;
	desktopPrecisionPairCountEl: HTMLElement;
	desktopPrecisionRmsEl: HTMLElement;
	desktopPrecisionWorkflowStatusEl: HTMLElement;
	desktopPrecisionPairListEl: HTMLElement;
	desktopSaveRegistrationButton: HTMLButtonElement;
	desktopExportJsonButton: HTMLButtonElement;
	desktopLogListEl: HTMLElement;
}

export interface ARSceneBundle {
	scene: THREE.Scene;
	camera: THREE.PerspectiveCamera;
	renderer: THREE.WebGLRenderer;
	controls: OrbitControls;
	reticle: THREE.Group;
	modelAnchor: THREE.Group;
}

export interface XRHitTestController {
	setup(): void;
	update(frame: XRFrame): void;
	hasGroundHit(): boolean;
	getHitPosition(target: THREE.Vector3): THREE.Vector3 | null;
	requestSession(): void;
}

export interface CoarsePlacementEstimate {
	position: THREE.Vector3;
	orientation: THREE.Quaternion;
	distanceMeters: number;
	headingDeg: number;
	accuracyMeters: number | null;
	sourceLabel: string;
}
